[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false
    
  
[[redirects]]
  from = "/sentence/*"
  to = "https://sentencing-explained.netlify.app/:splat 200" 
  status = 200
  force = true
  
  
 
